extracts:
  - name:  client
    uri:   "data/${env}/client_2017"
    check: "/spark/extract-check/client.sql"
  - name:  item
    uri:   "data/${env}/item_2017"
    check: "/spark/extract-check/item.sql"
  - name:  transaction
    uri:   "data/${env}/transaction_2017"
    check: "/spark/extract-check/transaction.sql"
  # unused extract
  - name:  ____bogus_extract_not_loaded____
    uri:   "hdfs://aaa.bbb"

transforms:
  - name:  client_spending
    check: "/spark/transform-check/client_spending.sql"
    sql:   "/spark/transform/client_spending.sql"
  - name:  item_purchase
    check: "/spark/transform-check/item_purchase.sql"
    sql:   "/spark/transform/item_purchase.sql"
  - name:  minor_purchase
    check: "/spark/transform-check/minor_purchase.sql"
    sql:   "/spark/transform/minor_purchase.sql"

loads:
  - name:   client_spending_out
    source: client_spending
    uri:    "/tmp/out/client_spending"
    # no partition_by
  - name:   item_purchase_out
    source: item_purchase
    uri:    "/tmp/out/item_purchase"
    # no partition_by
  - name:   minor_purchase_out
    source: minor_purchase
    uri:    "/tmp/out/minor_purchase"
    # no partition_by
